services:
  postgres-primary:
    image: postgres:15
    container_name: privatbank_postgres_primary
    environment:
      POSTGRES_DB: privatebank_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_primary_data:/var/lib/postgresql/data
      - ./init_primary.sql:/docker-entrypoint-initdb.d/init_primary.sql
      - ./schema:/schema
      - ./functions:/functions
      - ./monitoring:/monitoring
      - ./scripts:/scripts
      - .:/root
    command: >
      postgres
      -c wal_level=logical
      -c max_replication_slots=3
      -c max_wal_senders=3
    healthcheck:
      test: ["CMD-SHELL", "/root/primary_health_check.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - privatbank_network

  postgres-standby:
    image: postgres:15
    container_name: privatbank_postgres_standby
    environment:
      POSTGRES_DB: privatebank_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres_standby_data:/var/lib/postgresql/data
      - ./init_standby.sql:/docker-entrypoint-initdb.d/init_standby.sql
      - ./schema:/schema
      - ./functions:/functions
      - ./monitoring:/monitoring
      - ./scripts:/scripts
    depends_on:
      postgres-primary:
        condition: service_healthy
    command: >
      postgres
      -c wal_level=logical
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d privatebank_test"]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - privatbank_network

  scheduler:
    image: postgres:15
    container_name: privatbank_scheduler
    depends_on:
      postgres-primary:
        condition: service_healthy
    environment:
      PGPASSWORD: postgres
    volumes:
      - ./scripts:/scripts
    command: >
      bash -c "
      until pg_isready -h postgres-primary -p 5432 -U postgres; do 
        echo 'Waiting for primary postgres...'
        sleep 2
      done
      
      echo 'Primary PostgreSQL is ready, starting job scheduler...'
      
      while true; do
        psql -h postgres-primary -U postgres -d privatebank_test -c 'SELECT job_insert_transaction();' > /dev/null 2>&1
        sleep 5
        psql -h postgres-primary -U postgres -d privatebank_test -c 'SELECT job_update_status();' > /dev/null 2>&1 &
        sleep 3
      done
      "
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.1'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - privatbank_network

volumes:
  postgres_primary_data:
  postgres_standby_data:

networks:
  privatbank_network:
    driver: bridge
